### ISSUE TITLE
failure with server-side modules that use require

### ISSUE THREAD

**Issue by viz** [elastic-coders/serverless-runtime-webpack#5]
This plugin works great for my lambda functions, but I've found that webpack fails when I use a server-side module like node_redis or ioredis.

Both of these modules depend on redis-commands and redis-parser each of which `requires` modules or files that webpack can't find.

I understand this is because of how webpack processes the `require` statements, but my understanding of webpack runs out there.

Any idea how to resolve this? I'm using ES2015+stage0 features and I'd really like to avoid having to go and translate everything back into ES5.

**Comment by justingreenberg** [comment]
i would suggest double checking to make sure your webpack configuration is targeting node, and that you configured externals for your dependencies... 

``` js
  target: 'node',
  externals: [
    'aws-sdk',
    'node_redis'
  ]
```

when using webpack on server i typically use a helper to normalize node_modules dir and generate externals, using something like...

``` js
externals: function getExternals () {
  // path to node_modules
  var modulesPath = path.join(process.cwd(), 'node_modules')
  // read node modules directory folder names
  var nodeModules = fs.readdirSync(modulesPath)
  return nodeModules.reduce(function parseModules (externalMap, folderName) {
    // do not include npm executables
    if (folderName !== '.bin')
      // tag modules as commonjs
      externalMap[folderName] = 'commonjs ' + folderName
    return externalMap
  }, {})
}
```

most packages will have their own deps, so this ensures the dependency graph is complete for peer dependencies as well. note you must require `path` and `fs` for above or otherwise provide path to npm modules folder, and this must be written in es5 since it's not part of the build

**Comment by viz** [comment]
thanks Justin, seems like I'm almost there. The bundle is now being generated, but I'm now getting a serverless error when it tries to deploy. When trying to copy the external node module it's saying fs.copy is not a function. I know this is unlikely to be related to your plugin, but if you have any suggestions where to start looking I'd appreciate it.

**Comment by justingreenberg** [comment]
@viz sorry for delayed response, this seems to be a bug related to lib deps, please see #7 

were you able to solve your issue?

**Comment by thenikso** [comment]
should be fixed. Feel free to reopen otherwise
